[package]
name = "miette"
version = "5.8.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
description = "Fancy diagnostic reporting library and protocol for us mere mortals who aren't compiler hackers."
categories = ["rust-patterns"]
repository = "https://github.com/zkat/miette"
documentation = "https://docs.rs/miette"
license = "Apache-2.0"
readme = "README.md"
edition = "2018"
rust-version = "1.56.0"
exclude = ["images/", "tests/", "miette-derive/"]

[dependencies]
thiserror = "1.0.40"
miette-derive = { path = "miette-derive", version = "=5.8.0" }
once_cell = "1.8.0"
unicode-width = "0.1.9"

owo-colors = { version = "3.0.0", optional = true }
is-terminal = { version = "0.4.0", optional = true }
textwrap = { version = "0.15.0", optional = true }
supports-hyperlinks = { version = "2.0.0", optional = true }
supports-color = { version = "2.0.0", optional = true }
supports-unicode = { version = "2.0.0", optional = true }
backtrace = { version = "0.3.61", optional = true }
terminal_size = { version = "0.1.17", optional = true }
backtrace-ext = { version = "0.2.1", optional = true }
serde = { version = "1.0.162", optional = true }

[dev-dependencies]
semver = "1.0.4"

# Eyre devdeps
futures = { version = "0.3", default-features = false }
indenter = "0.3.0"
rustversion = "1.0"
trybuild = { version = "1.0.19", features = ["diff"] }
syn = { version = "2.0", features = ["full"] }
regex = "1.5"
lazy_static = "1.4"

[features]
default = []
no-format-args-capture = []
fancy-no-backtrace = [
    "owo-colors",
    "is-terminal",
    "textwrap",
    "terminal_size",
    "supports-hyperlinks",
    "supports-color",
    "supports-unicode",
]
fancy = ["fancy-no-backtrace", "backtrace", "backtrace-ext"]

[workspace]
members = ["miette-derive"]

[package.metadata.docs.rs]
all-features = true
